# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registrationform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from wsgiref.validate import validator
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator
from PyQt5.QtWidgets import QDialog, QApplication, QMessageBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(684, 843)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, 20, 591, 821))
        self.widget.setMouseTracking(True)
        self.widget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.widget.setAcceptDrops(True)
        self.widget.setStyleSheet("background-color:rgba(255, 255, 255);\n"
"border-radius:20px;")
        self.widget.setObjectName("widget")
        self.Tb1 = QtWidgets.QLineEdit(self.widget)
        self.Tb1.setGeometry(QtCore.QRect(220, 160, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb1.setFont(font)
        self.Tb1.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb1.setText("")
        self.Tb1.setObjectName("Tb1")
        self.Tb2 = QtWidgets.QLineEdit(self.widget)
        self.Tb2.setGeometry(QtCore.QRect(220, 220, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb2.setFont(font)
        self.Tb2.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb2.setText("")
        self.Tb2.setObjectName("Tb2")
        self.b1 = QtWidgets.QPushButton(self.widget)
        self.b1.setGeometry(QtCore.QRect(210, 710, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("QPushButton#b1{\n"
"background-color:rgb(255,191,16);\n"
"color:rgb(135,60,0);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#b1:pressed{\n"
"background-color:rgb(255,255,16);\n"
"}")
        self.b1.setObjectName("b1")
        self.label1 = QtWidgets.QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(-20, 70, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("background-color:rgb(255,191,16);\n"
"color:rgb(135,60,0);\n"
"padding-right:10px;")
        self.label1.setObjectName("label1")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 170, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 230, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 290, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.Tb3 = QtWidgets.QLineEdit(self.widget)
        self.Tb3.setGeometry(QtCore.QRect(220, 280, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb3.setFont(font)
        self.Tb3.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb3.setText("")
        self.Tb3.setObjectName("Tb3")
        #validator=QIntValidator
        x=QIntValidator
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        #self.lineEdit_7.setValidator(validator)
        self.lineEdit_7.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.Tb4 = QtWidgets.QLineEdit(self.widget)
        self.Tb4.setGeometry(QtCore.QRect(220, 340, 301, 40))
        """try:
                num=int(input())
        except ValueError:
                print('Enter Your age Properly')"""
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb4.setFont(font)
        self.Tb4.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb4.setText("")
        #self.Tb4.setValidator(x)
        self.Tb4.setObjectName("Tb4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setGeometry(QtCore.QRect(40, 410, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.Tb5 = QtWidgets.QLineEdit(self.widget)
        self.Tb5.setGeometry(QtCore.QRect(220, 400, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb5.setFont(font)
        self.Tb5.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb5.setText("")
        self.Tb5.setObjectName("Tb5")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setGeometry(QtCore.QRect(40, 580, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.Tb7 = QtWidgets.QLineEdit(self.widget)
        self.Tb7.setGeometry(QtCore.QRect(220, 570, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb7.setFont(font)
        self.Tb7.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb7.setText("")
        self.Tb7.setObjectName("Tb7")
        self.radioButton1 = QtWidgets.QRadioButton(self.widget)
        self.radioButton1.setGeometry(QtCore.QRect(220, 470, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton1.setFont(font)
        self.radioButton1.setStyleSheet("\n"
"color:rgba(15, 15, 15);\n"
"")
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton2 = QtWidgets.QRadioButton(self.widget)
        self.radioButton2.setGeometry(QtCore.QRect(330, 470, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton2.setFont(font)
        self.radioButton2.setStyleSheet("\n"
"\n"
"color:rgba(15, 15, 15);\n"
"")
        self.radioButton2.setObjectName("radioButton2")
        self.radioButton3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton3.setGeometry(QtCore.QRect(420, 470, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton3.setFont(font)
        self.radioButton3.setStyleSheet("\n"
"color:rgba(15, 15, 15);")
        self.radioButton3.setObjectName("radioButton3")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setGeometry(QtCore.QRect(40, 460, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setGeometry(QtCore.QRect(40, 520, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.Tb6 = QtWidgets.QLineEdit(self.widget)
        self.Tb6.setGeometry(QtCore.QRect(220, 510, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb6.setFont(font)
        self.Tb6.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb6.setText("")
        self.Tb6.setObjectName("Tb6")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_16.setGeometry(QtCore.QRect(40, 630, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setStyleSheet("\n"
"color:rgb(170, 85, 0);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.Tb8 = QtWidgets.QLineEdit(self.widget)
        self.Tb8.setGeometry(QtCore.QRect(220, 630, 301, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Tb8.setFont(font)
        self.Tb8.setStyleSheet("background-color:rgba(47,49,52,200);\n"
"color:rgba(255,255,255);\n"
"border-radius:20px;\n"
"padding-left:10px;\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"padding-bottom:3px;")
        self.Tb8.setText("")
        self.Tb8.setObjectName("Tb8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Tb1.setPlaceholderText(_translate("Form", "Enter Your First Name"))
        self.Tb2.setPlaceholderText(_translate("Form", "Enter Your Middle Name"))
        self.b1.setText(_translate("Form", "Submit"))
        self.label1.setText(_translate("Form", "                              Registration Form"))
        self.lineEdit_3.setText(_translate("Form", "First Name"))
        self.lineEdit_4.setText(_translate("Form", "Middle Name"))
        self.lineEdit_5.setText(_translate("Form", "Last Name"))
        self.Tb3.setPlaceholderText(_translate("Form", "Enter Your Last Name"))
        self.lineEdit_7.setText(_translate("Form", "Age"))
        self.Tb4.setPlaceholderText(_translate("Form", "Enter Your Age"))
        self.lineEdit_9.setText(_translate("Form", "BirthDate"))
        self.Tb5.setPlaceholderText(_translate("Form", "Enter Your Birtdate"))
        self.lineEdit_11.setText(_translate("Form", "Contact Number"))
        self.Tb7.setPlaceholderText(_translate("Form", "Enter Your Contact Number"))
        self.radioButton1.setText(_translate("Form", "Female"))
        self.radioButton2.setText(_translate("Form", "Male"))
        self.radioButton3.setText(_translate("Form", "Other"))
        self.lineEdit_13.setText(_translate("Form", "Gender"))
        self.lineEdit_14.setText(_translate("Form", "Address"))
        self.Tb6.setPlaceholderText(_translate("Form", "Enter Your Address"))
        self.lineEdit_16.setText(_translate("Form", "E-mail"))
        self.Tb8.setPlaceholderText(_translate("Form", "Enter Your email"))
        #QMessageBox.information(self,"Registrationform","Congo!! You Register Successfully.")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
   
    Form.show()
    sys.exit(app.exec_())
